### ISSUE TITLE
ループを入れると死ぬ?

### ISSUE THREAD

**Issue by icchyr** [kioowada/x86dump2dot#1]
```
#include <stdio.h>
int main() {
	int i, res;
	res = 0;
	for(i = 0; i < 10; i++) {
		res += i;
	}
	printf("%d", res);

	return 0;
}
```

`gcc main.c -o main` OK
`objdump -d main > main.disas` OK
`./dump2dot.php main.disas > main.dot` -> SEGVした

**Comment by kioowada** [comment]
basicblock.php:bb_checkExistance関数内にglobal文がぬけてた．

https://github.com/kioowada/x86dump2dot/tree/feature/fix_loop_sigsegv

ただし，printfの中を見に行こうとして死ぬ．
ライブラリの中までは見に行きたくないなあ

**Comment by kioowada** [comment]
とりあえず，上記対応をマージ
